name: ior+mobject@develop

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Mobject
      uses: actions/checkout@v3    
    - name: Checkout Spack
      uses: actions/checkout@v3
      with:
        repository: spack/spack
        path: ./spack
    - name: Checkout mochi-spack-packages
      uses: actions/checkout@v3
      with:
        repository: hyoklee/mochi-spack-packages
        path: ./mochi-spack-packages
    - name: Run spack install ior+mobject@develop
      run: |
        . ./spack/share/spack/setup-env.sh
        spack repo add ./mochi-spack-packages
        spack env create myenv ./spack.yaml
        spack env activate myenv
        spack add ior+mobject@develop
        spack install
        
