name: ior+mobject@develop

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spack
      uses: actions/checkout@v3
      with:
        repository: spack/spack
        path: ./spack
    - name: Checkout mochi-spack-packages
      uses: actions/checkout@v3
      with:
        repository: hyoklee/mochi-spack-packages
        path: ./mochi-spack-packages
    - name: Get Sources
      uses: actions/checkout@v3
    - name: Run spack install ior
      run: |
        . ./spack/share/spack/setup-env.sh
        spack repo add ./mochi-spack-packages
        spack install mobject@develop+bedrock
        spack load mobject
        spack install ior@develop+mobject
        spack load ior
        spack view --verbose symlink install ior@develop+mobject -i
        export LD_LIBRARY_PATH=$PWD/install/lib:$PWD/install/lib64
        echo $LD_LIBRARY_PATH
        ls
        ./prepare.sh
        ./configure --enable-bedrock
        make
        make check
        export MOBJECT_CLUSTER_FILE=/dev/shm/mobject.dat
        ior -a RADOS
